### ISSUE TITLE
I can not run the wallet on ubuntu 17.10

### ISSUE THREAD

**Issue by nextgenthemes** [Deviantcoin/Source#2]
./DeviantCoin-qt: error while loading shared libraries: libqrencode.so.4: cannot open shared object file: No such file or directory

I installed libblas3 libgfortran4 liblapack3 libqrupdate-dev libqrupdate1 but that did not solve it.

Do I need to compile that lib myself? You should include instructions how to run your wallet on the current Ubuntu release. Most desktops use 17.10 is my strong guess so your binary should work with it. This is not the first coin that has issues with that.

https://pkgs.org/download/libqrencode.so.4 I only found this but nothing for Ubuntu ...

**Comment by nextgenthemes** [comment]
figured it out one part a compile of libqrencode was needed.

with `sudo make install` and `sudo ldconfig` at the end I believe and then it worked.

but it turns out that it needs a older version of libboost installed to to run ... I think coins should provide binaries or build guides for linux and not just 16.04 but recent versions. I guess I could also compile and install that old version of libboost but I let it be for now.

**Comment by Deviantcoin** [comment]
Sorry forgot to check comments

**Comment by Deviantcoin** [comment]
Will release a binary for n 17.10

**Comment by likaigithub** [comment]
I also have the same problem on ubantu 16.04

**Comment by ScaMar** [comment]
as a workaround you can create such link:
sudo ln -s /usr/lib/x86_64-linux-gnu/libqrencode.so.3.4.4 /usr/lib/x86_64-linux-gnu/libqrencode.so.4
the wallet will start, but i made no deep tests, so i don't know if using QR functions need a specific function specific for libqrencode4 and not for libqrencode3.
The right way is to build libqrencode4 your own:
https://fukuchi.org/works/qrencode/

**Comment by ninjavz** [comment]
When ./configure I get these errors:
 ./configure: eval: line 2553: syntax error near unexpected token `('
 ./configure: eval: line 2553: `${SHELL} /home/user/qrencode-4.0.0/use/missing --is-lightweight'

Hence I cannot run the Wallet on Ubuntu 16.04

**Comment by ScaMar** [comment]
try with:
./autogen.sh && ./configure
as first command
