### ISSUE TITLE
setgenerate command crashes the qt-wallet

### ISSUE THREAD

**Issue by GiancarloLelli** [Deviantcoin/Source#33]
Hi team
Today, after having installed and synchronized the wallet, I wanted to start mining DeviantCoin using the QT client. I opened the Debug window and typed "setgenerate true 32" and after a couple if seconds the wallet crashed. 

Can you please help? I would like to mine DeviantCoin.

Thanks

**Comment by Toan** [comment]
Hi,

It's a POS coin, not a POW, you need coins for stake or creating MN
